export const recordStatus: { [key: number]: string } = {
  0: 'NoRecordStatus',
  1: 'Ready',
  2: 'Retrieved',
  3: 'Updated',
  4: 'Stale',
  5: 'Cancelled',
  6: 'AgentError',
  7: 'ChainUpdated',
  8: 'MissedCallBack',
  9: 'ChainReady',
  10: 'Delegated',
  11: '-MAX-',
};

export const recordType: { [key: number]: string } = {
  0: 'NoRecordType',
  1: 'Unknown',
  2: 'General',
  3: 'CampaignRescheduled',
  4: 'PersonalRescheduled',
  5: 'PersonalCallBack',
  6: 'CampaignCallBack',
  7: 'NoCall',
  8: '-MAX-',
};

export const callResult: { [key: number]: string } = {
  0: 'Ok',
  1: 'Transferred',
  2: 'Conferenced',
  3: 'General Error',
  4: 'System Error',
  5: 'Remote Release',
  6: 'Busy',
  7: 'No Answer',
  8: 'SIT Detected',
  9: 'Answering Machine',
  10: 'All Trunks Busy',
  11: 'SIT Invalid Numb',
  12: 'SIT Vacant',
  13: 'SIT Oper Intercept',
  14: 'SIT Unknown',
  15: 'SIT No Circuit',
  16: 'SIT Reorder',
  17: 'Fax Detected',
  18: 'Queue Full',
  19: 'Cleared',
  20: 'Overflowed',
  21: 'Abandoned',
  22: 'Redirected',
  23: 'Forwarded',
  24: 'Consult',
  25: 'Pickedup',
  26: 'Dropped',
  27: 'Dropped No Answer',
  28: 'Unknown',
  29: 'Covered',
  30: 'Converse-On',
  31: 'Bridged',
  32: 'Silence',
  33: 'Answer',
  34: 'NuTone',
  35: 'NoDialTone',
  36: 'NoProgress',
  37: 'NoRingBack',
  38: 'NoEstablishe',
  39: 'Pager Detected',
  40: 'Wrong Party',
  41: 'Dial Error',
  42: 'Call Drop Error',
  43: 'Switch Error',
  44: 'No Free Port Error',
  45: 'Transfer Error',
  46: 'Stale',
  47: 'Agent CallBack Error',
  48: 'Group CallBack Error',
  49: 'Deafened',
  50: 'Held',
  51: 'Do Not Call',
  52: 'Cancel Record',
  53: 'Wrong Number',
};

export const deviceType: { [key: number]: string } = {
  0: 'No Contact Type',
  1: 'Home Phone',
  2: 'Direct Business Phone',
  3: 'Business Phone With Extension',
  4: 'Mobile',
  5: 'Vacation Phone',
  6: 'Pager',
  7: 'Modem',
  8: 'Voice Mail',
  9: 'Pin Pager',
  10: 'E-Mail',
  11: 'Instant Messaging',
  12: '-MAX-',
};
