export const campaigns = {
  status: {
    code: 0,
  },
  data: [
    {
      $class: 'CfgFolder',
      id: 124,
      name: 'Campaigns',
      type: 27,
      size: 7,
      items: [
        {
          $class: 'CfgCampaign',
          id: 138204,
          name: 'new template-055fa4a6',
          items: [
            {
              $class: 'CfgCampaignGroup',
              id: 137851,
              groupId: 261,
              campaignId: 138204,
              name: 'new template-055fa4a6@CXContactSMSGroup',
              target: 80,
              dialMode: 'Power',
              optMethod: 'WaitTime',
              voiceTransferDestination: '+14085507006',
              trunkGroup: 'None',
              statServer: 'SS',
              schedule: 'Schedule',
              maxQueueSize: 0,
              ivrProfile: 'None',
            },
          ],
          callingLists: [],
        },
        {
          $class: 'CfgCampaign',
          id: 138260,
          name: 'voice template-869dca0b',
          items: [
            {
              $class: 'CfgCampaignGroup',
              id: 137904,
              groupId: 229,
              campaignId: 138260,
              name: 'voice template-869dca0b@AG_Test_1',
              target: 0,
              dialMode: 'Preview',
              optMethod: 'WaitTime',
              voiceTransferDestination: '3510',
              trunkGroup: 'Outbound_usw1',
              statServer: 'SS',
              schedule: 'Schedule',
              maxQueueSize: 0,
              ivrProfile: 'None',
            },
          ],
          callingLists: [
            {
              $class: 'CfgCallingList',
              id: 705204,
              name: 'cm_test_1697097483930',
              weight: 10,
            },
          ],
        },
        {
          $class: 'CfgCampaign',
          id: 138219,
          name: 'EMail_CT-667eedd8',
          items: [
            {
              $class: 'CfgCampaignGroup',
              id: 137863,
              groupId: 264,
              campaignId: 138219,
              name: 'EMail_CT-667eedd8@CXContactEMailGroup',
              target: 10,
              dialMode: 'Power',
              optMethod: 'WaitTime',
              voiceTransferDestination: '+14085507006',
              trunkGroup: 'None',
              statServer: 'SS',
              schedule: 'Schedule',
              maxQueueSize: 0,
              ivrProfile: 'None',
            },
          ],
          callingLists: [
            {
              $class: 'CfgCallingList',
              id: 705204,
              name: 'cm_test_1697097483930',
              weight: 100,
            },
          ],
        },
        {
          $class: 'CfgFolder',
          id: 138741,
          name: 'upp folder',
          type: 27,
          size: 2,
          items: [
            {
              $class: 'CfgCampaign',
              id: 138259,
              name: 'email var template-98f6fc64',
              items: [
                {
                  $class: 'CfgCampaignGroup',
                  id: 137903,
                  groupId: 264,
                  campaignId: 138259,
                  name: 'email var template-98f6fc64@CXContactEMailGroup',
                  target: 10,
                  dialMode: 'Power',
                  optMethod: 'WaitTime',
                  voiceTransferDestination: '+14085507006',
                  trunkGroup: 'None',
                  statServer: 'SS',
                  schedule: 'Schedule',
                  maxQueueSize: 0,
                  ivrProfile: 'None',
                },
              ],
              callingLists: [],
            },
            {
              $class: 'CfgFolder',
              id: 138742,
              name: 'midle folder',
              type: 27,
              size: 1,
              items: [
                {
                  $class: 'CfgCampaign',
                  id: 138207,
                  name: 'rg_test-07737c1b',
                  items: [
                    {
                      $class: 'CfgCampaignGroup',
                      id: 137854,
                      groupId: 261,
                      campaignId: 138207,
                      name: 'rg_test-07737c1b@CXContactSMSGroup',
                      target: 10,
                      dialMode: 'Power',
                      optMethod: 'WaitTime',
                      voiceTransferDestination: '+14085507006',
                      trunkGroup: 'None',
                      statServer: 'SS',
                      schedule: 'Schedule',
                      maxQueueSize: 0,
                      ivrProfile: 'None',
                    },
                    {
                      $class: 'CfgFolder',
                      id: 138743,
                      name: 'internal folder',
                      type: 38,
                      size: 1,
                      items: [
                        {
                          $class: 'CfgCampaignGroup',
                          id: 137906,
                          groupId: 310,
                          campaignId: 138207,
                          name: 'rg_test-07737c1b@AGRP_IT_Italy',
                          target: 80,
                          dialMode: 'Predict',
                          optMethod: 'BusyFactor',
                          voiceTransferDestination: 'None',
                          trunkGroup: 'None',
                          statServer: 'None',
                          schedule: 'Schedule',
                          maxQueueSize: 0,
                          ivrProfile: 'None',
                        },
                      ],
                    },
                  ],
                  callingLists: [],
                },
              ],
            },
          ],
        },
        {
          $class: 'CfgFolder',
          id: 138744,
          name: 'test_folder_name',
          type: 27,
          size: 1,
          items: [
            {
              $class: 'CfgFolder',
              id: 138751,
              name: 'test1_folder_name',
              type: 27,
              size: 1,
              items: [
                {
                  $class: 'CfgFolder',
                  id: 138752,
                  name: 'test2_folder_name',
                  type: 27,
                  size: 1,
                  items: [
                    {
                      $class: 'CfgFolder',
                      id: 138753,
                      name: 'test3_folder_name',
                      type: 27,
                      size: 1,
                      items: [
                        {
                          $class: 'CfgCampaign',
                          id: 138262,
                          name: 'campaign_zihansky',
                          items: [
                            {
                              $class: 'CfgFolder',
                              id: 138755,
                              name: 'CampaignGroupsFolder',
                              type: 38,
                              size: 1,
                              items: [
                                {
                                  $class: 'CfgFolder',
                                  id: 138756,
                                  name: 'OneMoreFolder',
                                  type: 38,
                                  size: 1,
                                  items: [
                                    {
                                      $class: 'CfgCampaignGroup',
                                      id: 137907,
                                      groupId: 243,
                                      campaignId: 138262,
                                      name: 'campaign_zihansky@AG_Test_2',
                                      target: 80,
                                      dialMode: 'Predict',
                                      optMethod: 'BusyFactor',
                                      voiceTransferDestination: 'None',
                                      trunkGroup: 'None',
                                      statServer: 'None',
                                      schedule: 'Schedule',
                                      maxQueueSize: 0,
                                      ivrProfile: 'None',
                                    },
                                  ],
                                },
                              ],
                            },
                          ],
                          callingLists: [
                            {
                              $class: 'CfgCallingList',
                              id: 711861,
                              name: 'ga_list_001',
                              weight: 10,
                            },
                            {
                              $class: 'CfgCallingList',
                              id: 705333,
                              name: 'lb_test_20231012_091210_part_Rule-3 ALL',
                              weight: 10,
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          $class: 'CfgFolder',
          id: 138745,
          name: 'up main',
          type: 27,
          size: 1,
          items: [
            {
              $class: 'CfgFolder',
              id: 138746,
              name: 'folder1',
              type: 27,
              size: 2,
              items: [
                {
                  $class: 'CfgFolder',
                  id: 138747,
                  name: 'folder2',
                  type: 27,
                  size: 1,
                  items: [
                    {
                      $class: 'CfgFolder',
                      id: 138749,
                      name: 'folder4',
                      type: 27,
                      size: 1,
                      items: [
                        {
                          $class: 'CfgFolder',
                          id: 138750,
                          name: 'folder5',
                          type: 27,
                          size: 1,
                          items: [
                            {
                              $class: 'CfgCampaign',
                              id: 138261,
                              name: 'SMS Template 001-ebb8e9d5',
                              items: [
                                {
                                  $class: 'CfgCampaignGroup',
                                  id: 137905,
                                  groupId: 261,
                                  campaignId: 138261,
                                  name: 'SMS Template 001-ebb8e9d5@CXContactSMSGroup',
                                  target: 10,
                                  dialMode: 'Power',
                                  optMethod: 'WaitTime',
                                  voiceTransferDestination: '+14085507006',
                                  trunkGroup: 'Outbound_usw1',
                                  statServer: 'SS',
                                  schedule: 'Schedule',
                                  maxQueueSize: 0,
                                  ivrProfile: 'gsw_ivr_profile',
                                },
                              ],
                              callingLists: [],
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
                {
                  $class: 'CfgFolder',
                  id: 138748,
                  name: 'folder3',
                  type: 27,
                  size: 0,
                  items: [],
                },
              ],
            },
          ],
        },
        {
          $class: 'CfgCampaign',
          id: 138263,
          name: 'test_azihan',
          items: [
            {
              $class: 'CfgCampaignGroup',
              id: 137908,
              groupId: 299,
              campaignId: 138263,
              name: 'test_azihan@AgentGroup2',
              target: 80,
              dialMode: 'Predict',
              optMethod: 'BusyFactor',
              voiceTransferDestination: 'None',
              trunkGroup: 'None',
              statServer: 'None',
              schedule: 'Schedule',
              maxQueueSize: 0,
              ivrProfile: 'None',
            },
            {
              $class: 'CfgFolder',
              id: 138758,
              name: 'NewCGFolder',
              type: 38,
              size: 1,
              items: [
                {
                  $class: 'CfgCampaignGroup',
                  id: 137909,
                  groupId: 254,
                  campaignId: 138263,
                  name: 'test_azihan@cxc_qa',
                  target: 80,
                  dialMode: 'Predict',
                  optMethod: 'BusyFactor',
                  voiceTransferDestination: 'None',
                  trunkGroup: 'None',
                  statServer: 'None',
                  schedule: 'Schedule',
                  maxQueueSize: 0,
                  ivrProfile: 'None',
                },
              ],
            },
          ],
          callingLists: [
            {
              $class: 'CfgCallingList',
              id: 711865,
              name: 'cm_test_1698674035716',
              weight: 10,
            },
          ],
        },
      ],
    },
  ],
};
